program prjPedidos;

uses
  Vcl.Forms,
  untPrincipal in 'untPrincipal.pas' {frmPrincipal},
  untLogin in 'untLogin.pas' {frmLogin},
  untBiblioteca in 'untBiblioteca.pas',
  unitConfiguracoes in 'unitConfiguracoes.pas',
  untSplash in 'untSplash.pas' {frmSplash},
  PedidoUsuariosVO in '..\VO\PedidoUsuariosVO.pas',
  PedidoUsuarioController in '..\Controller\PedidoUsuarioController.pas',
  Vcl.Themes,
  Vcl.Styles,
  PedidoEmpresasVO in '..\VO\PedidoEmpresasVO.pas',
  PedidoProdutosVO in '..\VO\PedidoProdutosVO.pas',
  untExportacaoDeProdutos in 'untExportacaoDeProdutos.pas' {frmExportacaoDeProdutos},
  untSQLs in 'untSQLs.pas' {frmSQLs},
  PedidoSqlVO in '..\VO\PedidoSqlVO.pas',
  PedidoSqlController in '..\Controller\PedidoSqlController.pas',
  untConexao in 'untConexao.pas' {frmConexao},
  PedidoFuncionariosVO in '..\VO\PedidoFuncionariosVO.pas',
  PedidoFuncionariosController in '..\Controller\PedidoFuncionariosController.pas',
  PedidoFormaPagamentoVO in '..\VO\PedidoFormaPagamentoVO.pas',
  PedidoClientesVO in '..\VO\PedidoClientesVO.pas',
  untExportacaoDeClientes in 'untExportacaoDeClientes.pas' {frmExportacaoDeClientes},
  PedidoClientesController in '..\Controller\PedidoClientesController.pas',
  untExportacaoDeFormaPagamento in 'untExportacaoDeFormaPagamento.pas' {frmExportacaoDeFormaPagamento},
  PedidoFormaPagamentoController in '..\Controller\PedidoFormaPagamentoController.pas',
  PedidoConexaoVO in '..\VO\PedidoConexaoVO.pas',
  PedidoConexaoController in '..\Controller\PedidoConexaoController.pas',
  untExportacaoDeFuncionarios in 'untExportacaoDeFuncionarios.pas' {frmExportacaoDeFuncionarios},
  untPedidos in 'untPedidos.pas' {frmPedidos},
  PedidoProdutosController in '..\Controller\PedidoProdutosController.pas',
  untPesquisarClientes in 'untPesquisarClientes.pas' {frmPesquisarClientes},
  untPesquisarFuncionarios in 'untPesquisarFuncionarios.pas' {frmPesquisarFuncionarios},
  untPesquisarFormaPG in 'untPesquisarFormaPG.pas' {frmPesquisarFormaPG},
  untPesquisarProdutos in 'untPesquisarProdutos.pas' {frmPesquisarProdutos},
  BaseLocalClientesVO in '..\VO\BaseLocalClientesVO.pas',
  BaseLocalUnidadesVO in '..\VO\BaseLocalUnidadesVO.pas',
  BaseLocalProdutosVO in '..\VO\BaseLocalProdutosVO.pas',
  BaseLocalFuncionariosVO in '..\VO\BaseLocalFuncionariosVO.pas',
  BaseLocalUsuariosVO in '..\VO\BaseLocalUsuariosVO.pas',
  BaseLocalFormasPagamentoVO in '..\VO\BaseLocalFormasPagamentoVO.pas',
  untDescontoAcrescimo in 'untDescontoAcrescimo.pas' {frmDescontoAcrescimo},
  untFinalizarVenda in 'untFinalizarVenda.pas' {frmFinalizarVenda},
  BaseLocalVendaCabecalhoVO in '..\VO\BaseLocalVendaCabecalhoVO.pas',
  BaseLocalVendaDetalheVO in '..\VO\BaseLocalVendaDetalheVO.pas',
  BaseLocalTotalTipoPagtoVO in '..\VO\BaseLocalTotalTipoPagtoVO.pas',
  untMenuPrincipal in 'untMenuPrincipal.pas' {frmMenuPrincipal},
  BaseLocalVendaCabecalhoController in '..\Controller\BaseLocalVendaCabecalhoController.pas',
  BaseLocalVendaDetalheController in '..\Controller\BaseLocalVendaDetalheController.pas',
  BaseLocalTotalTipoPagtoController in '..\Controller\BaseLocalTotalTipoPagtoController.pas',
  BaseLocalClientesController in '..\Controller\BaseLocalClientesController.pas',
  BaseLocalFuncionariosController in '..\Controller\BaseLocalFuncionariosController.pas',
  BaseLocalUsuariosController in '..\Controller\BaseLocalUsuariosController.pas',
  untCadastrarUsuarios in 'untCadastrarUsuarios.pas' {frmCadastrarUsuarios},
  BaseLocalEmpresaController in '..\Controller\BaseLocalEmpresaController.pas',
  BaseLocalEmpresaVO in '..\VO\BaseLocalEmpresaVO.pas',
  untCadastrarProdutos in 'untCadastrarProdutos.pas' {frmCadastrarProdutos},
  untCadastrarUnidades in 'untCadastrarUnidades.pas' {frmCadastrarUnidades},
  untCadastrarFuncionarios in 'untCadastrarFuncionarios.pas' {frmCadastrarFuncionarios},
  untCadastrarClientes in 'untCadastrarClientes.pas' {frmCadastrarClientes},
  untCadastrarEmpresa in 'untCadastrarEmpresa.pas' {frmCadastrarEmpresa},
  untCadastrarFormaPG in 'untCadastrarFormaPG.pas' {frmCadastrarFormaPG},
  untPesquisarEmpresa in 'untPesquisarEmpresa.pas' {frmPesquisarEmpresa},
  untPesquisarUsuarios in 'untPesquisarUsuarios.pas' {frmPesquisarUsuarios},
  untPesquisarUnidades in 'untPesquisarUnidades.pas' {frmPesquisarUnidades},
  BaseLocalUnidadesController in '..\Controller\BaseLocalUnidadesController.pas',
  BaseLocalProdutosController in '..\Controller\BaseLocalProdutosController.pas',
  BaseLocalFormasPagamentoController in '..\Controller\BaseLocalFormasPagamentoController.pas',
  untExportacoes in 'untExportacoes.pas' {frmExportacoes},
  untCadastroParametros in 'untCadastroParametros.pas' {frmCadastroParametros},
  BaseLocalParametrosVO in '..\VO\BaseLocalParametrosVO.pas',
  BaseLocalParametrosController in '..\Controller\BaseLocalParametrosController.pas',
  BaseLocalPedidoCabecalhoVO in '..\VO\BaseLocalPedidoCabecalhoVO.pas',
  BaseLocalPedidoDetalheVO in '..\VO\BaseLocalPedidoDetalheVO.pas',
  BaseLocalPedidoCabecalhoController in '..\Controller\BaseLocalPedidoCabecalhoController.pas',
  BaseLocalPedidoDetalheController in '..\Controller\BaseLocalPedidoDetalheController.pas',
  BaseLocalSangriaVO in '..\VO\BaseLocalSangriaVO.pas',
  BaseLocalSuprimentoVO in '..\VO\BaseLocalSuprimentoVO.pas',
  BaseLocalSuprimentoController in '..\Controller\BaseLocalSuprimentoController.pas',
  BaseLocalSangriaController in '..\Controller\BaseLocalSangriaController.pas',
  untCadastrarSuprimento in 'untCadastrarSuprimento.pas' {frmCadastrarSuprimento},
  untCadastrarSangria in 'untCadastrarSangria.pas' {frmCadastrarSangria},
  untPreviaCaixa in 'untPreviaCaixa.pas' {frmPreviaCaixa},
  untTelaDePedido in 'untTelaDePedido.pas' {frmTelaDePedido},
  untCancelamentoItemPedido in 'untCancelamentoItemPedido.pas' {frmCancelamentoItemPedido},
  untObservacao in 'untObservacao.pas' {frmObservacao},
  untFechamentoCaixa in 'untFechamentoCaixa.pas' {frmFechamentoCaixa},
  untPedidosCancelados in 'untPedidosCancelados.pas' {frmPedidosCancelados},
  untPedidosPendentes in 'untPedidosPendentes.pas' {frmPedidosPendentes},
  untCancelamentoDeVenda in 'untCancelamentoDeVenda.pas' {frmCancelamentoDeVenda},
  untPainelRelatorios in 'untPainelRelatorios.pas' {frmPainelRelatorios},
  untRelProdutosMaisVendidos in 'untRelProdutosMaisVendidos.pas' {frmRelProdutosMaisVendidos},
  untPesquisarNCM in 'untPesquisarNCM.pas' {frmPesquisarNCM},
  untPesquisarCEST in 'untPesquisarCEST.pas' {frmPesquisarCEST},
  untExportarXML in 'untExportarXML.pas' {frmExportarXML},
  untConsultarPagarFidelidade in 'untConsultarPagarFidelidade.pas' {frmConsultarPagarFidelidade},
  untConsultarFidelidade in 'untConsultarFidelidade.pas' {frmConsultarFidelidade},
  untIntegracaoFidelidade in 'Fidelidade\untIntegracaoFidelidade.pas',
  untCadastrarFidelidade in 'Fidelidade\untCadastrarFidelidade.pas' {frmCadastrarFidelidade},
  untRelVendasPorCFOP in 'untRelVendasPorCFOP.pas' {frmRelVendasPorCFOP},
  untRelVendasPorPeriodo in 'untRelVendasPorPeriodo.pas' {frmRelVendasPorPeriodo};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.Run;
end.
